
extends:
  - '@commitlint/config-conventional'

rules:
  type-enum:
    - 2
    - always
    - [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'test',
        'chore',
        'perf',
        'ci',
        'build',
        'revert'
      ]
  
  scope-enum:
    - 2
    - always
    - [
        'api',
        'ui',
        'components',
        'utils',
        'config',
        'docs',
        'tests',
        'reading-plan',
        'bible',
        'progress',
        'theme',
        'navigation',
        'bookmarks',
        'search',
        'translations',
        'phase-1',
        'phase-2',
        'phase-3',
        'release'
      ]
  
  subject-case:
    - 2
    - never
    - ['sentence-case', 'start-case', 'pascal-case', 'upper-case']
  
  subject-empty:
    - 2
    - never
  
  subject-full-stop:
    - 2
    - never
    - '.'
  
  type-case:
    - 2
    - always
    - 'lower-case'
  
  type-empty:
    - 2
    - never
  
  scope-case:
    - 2
    - always
    - 'lower-case'
  
  header-max-length:
    - 2
    - always
    - 72
  
  body-leading-blank:
    - 1
    - always
  
  body-max-line-length:
    - 2
    - always
    - 100
  
  footer-leading-blank:
    - 1
    - always
  
  footer-max-line-length:
    - 2
    - always
    - 100

helpUrl: 'https://github.com/conventional-changelog/commitlint/#what-is-commitlint'
