[build]
  base = "app"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Redirect all routes to index.html for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
